### ISSUE TITLE
Refactoring of code. 

### ISSUE THREAD

**Issue by Muhib007dev** [Muhib007dev/CoronaApiInJava#11]

**Comment by Astro0mar** [comment]
I couldn't understand

**Comment by Muhib007dev** [comment]
If you look into the code. The logic of web-scraping is in the controller and a lot of unnecessary comments. I want someone to clean up my code and put up the code in their respective class or packages.

**Comment by Muhib007dev** [comment]
I did web-scraping from two different websites, so we can also separate that up in the code by creating two different classes.

**Comment by Muhib007dev** [comment]
I hope you got the context

**Comment by Astro0mar** [comment]
I am sorry but is it require knowledge in web-scraping ?.. I am novice in open source contribution

**Comment by Muhib007dev** [comment]
No. it doesn't. Do look into the code first.

**Comment by mihirterna** [comment]
Hi @Muhib007dev , I am working on this one, Can you please assign this to me?

**Comment by mihirterna** [comment]
Hi @Muhib007dev , Created PR #12 for above change, it seems automatic deployment is not working following error is present in netlify logs :
mvn clean install
bash: mvn: command not found.

Please check,  Thanks.

**Comment by mihirterna** [comment]
Hi @Muhib007dev , hacktoberfest.digitalocean.com is showing, this Project not participating. Please confirm whether this issue is eligible for hacktoberfest 2021.

**Comment by Muhib007dev** [comment]
It is just the label of hacktoberfest that I have to add right?

**Comment by Muhib007dev** [comment]
> Hi @Muhib007dev , Created PR #12 for above change, it seems automatic deployment is not working following error is present in netlify logs : mvn clean install bash: mvn: command not found.
> 
> Please check, Thanks.

I am not using netlify for deployment anymore I am using herokuapp, we can ignore that. I will review you PR shortly

**Comment by mihirterna** [comment]
Once you approve pull request, kindly add label hacktoberfest-accepted to PR. That would make PR eligible for contest. Thanks.

**Comment by Muhib007dev** [comment]
Sure. I will do that definitely.

**Comment by Muhib007dev** [comment]
This issue will remain open till hacktoberfest ends, anyone can contribute if it seems any further refactoring is required in the code.
